export const keywords = {
  "Ai Engineer": ["ai", "ml", "artificial intelligence", "kecerdasan buatan", "ai engineer", "neural network", "deep learning", "model ai", "pengenalan pola", "pattern recognition", "computer vision", "nlp", "machine learning ai", "large language model", "llm", "openai", "model inference", "ai system", "ai pipeline", "chatbot", "rnn", "gpt", "transformer model", "self supervised", "ai framework", "huggingface", "fine tuning", "prompt engineering"],
  "Back-End Developer Python": ["back end", "backend python", "back end python", "django", "flask", "fastapi", "python rest api", "python backend", "web backend python", "server python", "python framework", "orm django", "uvicorn", "wsgi", "asgi", "backend dev python", "server", "api", "backend", "be"],
  "Back-End Developer JavaScipt": ["back end", "back-end", "be", "backend js", "back end javascript", "nodejs", "expressjs", "rest api javascript", "javascript backend", "node", "npm", "backend web js", "server side js", "json api", "mongo express node", "mern backend", "sequelize js", "javascript server", "http server js"],
  "Data Scientist": ["data scientist", "data science", "data analyst", "data mining", "machine learning", "pandas", "numpy", "matplotlib", "analisis data", "statistik", "regresi", "clustering", "classification", "data preprocessing", "dataset", "feature engineering", "model training", "python data", "jupyter", "eda", "model evaluation", "predictive modelling"],
  "Front-End Web Developer": ["front", "end", "fe", "frontend", "front-end", "web developer", "html", "css", "javascript", "react", "vue", "svelte", "dom", "responsive", "frontend framework", "ui", "ux", "css flexbox", "css grid", "tailwind", "bootstrap", "frontend design", "spa", "client side", "axios frontend", "web styling", "web interactivity"],
  "GEN AI Engineer": ["gen ai", "generative ai", "ai generatif", "text to image", "image generation", "stable diffusion", "llm", "rag", "retrieval augmented generation", "vector db", "embedding", "fine tuning llm", "chatbot genai", "openai api", "anthropic", "ai content generation", "genai pipeline", "prompt engineering advanced"],
  "Google Cloud Professional": ["google cloud", "gcp", "cloud run", "cloud function", "cloud storage", "compute engine", "bigquery", "gke", "google cloud certification", "cloud architect", "cloud engineer", "firebase gcp", "pubsub", "gcp devops", "service account", "cloud networking", "gcp training"],
  "iOS Developer": ["ios", "ios developer", "swift", "swiftui", "xcode", "cocoapods", "objective c", "iphone development", "apple developer", "appstore", "ios sdk", "mobile developer ios", "ui kit", "ios layout", "ios simulator", "ios app"],
  "MLOPS Engineer": ["mlops", "machine learning ops", "deployment ml", "ml model deployment", "model serving", "ml pipeline", "airflow", "kubeflow", "mlflow", "docker ml", "kubernetes ml", "continuous training", "feature store", "monitoring ml", "ml system", "scalable ml", "model registry", "automl pipeline"],
  "Multi-Platform App Developer": ["multi platform", "cross platform", "flutter", "dart", "react native", "kotlin multiplatform", "hybrid app", "mobile cross platform", "mobile web app", "ui mobile hybrid", "build apk ios", "flutter widget", "cross platform toolkit", "mobile multiplatform"],
  "React Developer": ["react", "reactjs", "react developer", "react hooks", "jsx", "vite react", "redux", "nextjs", "react component", "react state", "react context", "spa react", "router react", "react ui", "frontend react", "react dom"]
}