import re

# JOB_ROLE_KEYWORDS (update)
JOB_ROLE_KEYWORDS = {
  "Google Cloud Professional": [
    "gcp",
    "google cloud",
    "google cloud platform",
    "gcloud",
    "cloud engineer",
    "cloud architect",
    "cloud computing",
    "cloud infra",
    "gcp cert",
    "gcp certification",
    "professional cloud architect",
    "associate cloud engineer",
    "gke",
    "gke cluster",
    "kubernetes gcp",
    "gcp vm",
    "compute engine",
    "app engine",
    "cloud run",
    "cloud functions",
    "cloud storage",
    "bigquery",
    "bigtable",
    "spanner",
    "pubsub",
    "pub sub",
    "pub/sub",
    "vpc gcp",
    "cloud sql",
    "iam gcp",
    "gcp networking",
    "gcp monitoring",
    "stackdriver",
    "terraform gcp",
    "deployment manager",
    "gsutil",
    "gcloud cli",
    "cloud logging",
    "cloud build",
    "artifact registry",
    "cloud armor",
    "load balancer gcp",
    "gcp security",
    "gcp billing",
    "service accounts",
    "cloud composer",
    "dataflow",
    "dataproc",
    "vertex ai",
    "cloud"
  ],

  "Gen AI Engineer": [
    "gen ai",
    "generative ai",
    "ai generation",
    "prompt engineer",
    "prompting",
    "prompt design",
    "fine tune",
    "finetune llm",
    "rag",
    "rag pipeline",
    "retrieval augmented generation",
    "embedding model",
    "vector store",
    "vector db",
    "faiss",
    "chromadb",
    "pinecone",
    "llm app",
    "llm engineering",
    "inference",
    "llm inference",
    "openai api",
    "claude api",
    "gemini api",
    "lora",
    "qlora",
    "sft",
    "rlhf",
    "function calling",
    "tool calling",
    "system prompt",
    "context window",
    "tokenization",
    "transformer models",
    "diffusion models",
    "image generation",
    "text generation",
    "rag evaluation",
    "model prompt tuning",
    "agentic workflows",
    "ai agents",
    "multi agent system",
    "generation quality",
    "hallucination reduction",
    "prompt optimization",
    "prompt patterns",
    "ai workflow",
    "embedding search",
    "knowledge retrieval",
    "context injection",
    "ai orchestration"
  ],

  "AI Engineer": [
    "machine learning",
    "ml",
    "ml engineer",
    "deep learning",
    "dl",
    "neural network",
    "neural nets",
    "cnn",
    "rnn",
    "transformer",
    "llm",
    "bert",
    "gpt",
    "supervised learning",
    "unsupervised learning",
    "reinforcement learning",
    "ml pipeline",
    "model training",
    "model inference",
    "mlops",
    "data preprocessing",
    "feature engineering",
    "model deployment",
    "tensorflow",
    "pytorch",
    "sklearn",
    "scikit learn",
    "numpy",
    "pandas",
    "data augmentation",
    "hyperparameter tuning",
    "cross validation",
    "classification",
    "regression",
    "clustering",
    "recommendation system",
    "vectorization",
    "onnx",
    "quantization",
    "model evaluation",
    "confusion matrix",
    "roc auc",
    "f1 score",
    "ml model optimization",
    "production model",
    "ml architecture",
    "ml notebook",
    "jupyter",
    "colab",
    "ai engineer"
  ],

  "Front-End Web Developer": [
    "frontend",
    "front end",
    "front-end",
    "fe dev",
    "ui developer",
    "web ui",
    "html",
    "html5",
    "css",
    "css3",
    "sass",
    "scss",
    "tailwind",
    "bootstrap",
    "js",
    "javascript",
    "ecmascript",
    "react",
    "reactjs",
    "react js",
    "nextjs",
    "next js",
    "vue",
    "vuejs",
    "vue js",
    "svelte",
    "sveltekit",
    "vite",
    "webpack",
    "parcel",
    "babel",
    "dom",
    "virtual dom",
    "spa",
    "single page application",
    "csr",
    "ssr react",
    "hydration",
    "frontend framework",
    "ui component",
    "responsive web",
    "mobile first",
    "accessibility",
    "aria",
    "frontend performance",
    "client side",
    "fetch api",
    "rest frontend",
    "axios frontend",
    "typescript frontend"
  ],

  "Back-End Developer Python": [
    "backend python",
    "python backend",
    "python server",
    "django",
    "django rest",
    "drf",
    "flask",
    "fastapi",
    "starlette",
    "uvicorn",
    "gunicorn",
    "sqlalchemy",
    "orm python",
    "python api",
    "rest api python",
    "microservice python",
    "async python",
    "aiohttp",
    "python webserver",
    "python services",
    "postgres python",
    "mysql python",
    "mongodb python",
    "redis python",
    "celery",
    "queue worker python",
    "jwt python",
    "auth python",
    "server side python",
    "lambda python",
    "python backend dev",
    "python web dev",
    "model serializer",
    "django views",
    "django orm",
    "flask app",
    "fastapi router",
    "pydantic",
    "python mvc",
    "python wsgi",
    "python asgi",
    "python backend patterns",
    "python deployment",
    "python container",
    "python docker"
  ],

  "Back-End Developer JavaScript": [
    "backend js",
    "backend javascript",
    "javascript backend",
    "node",
    "nodejs",
    "node js",
    "express",
    "expressjs",
    "express js",
    "koa",
    "nestjs",
    "server side js",
    "javascript server",
    "js backend dev",
    "rest api js",
    "api backend js",
    "javascript microservice",
    "npm",
    "yarn",
    "typeorm",
    "prisma",
    "mongoose",
    "mongodb node",
    "postgres node",
    "mysql node",
    "sequelize",
    "jwt node",
    "auth node",
    "node worker",
    "event loop",
    "async await",
    "callback",
    "promise",
    "node router",
    "node middleware",
    "node controller",
    "serverless js",
    "lambda javascript",
    "firebase functions",
    "bun backend",
    "hono js",
    "edge functions",
    "http server js",
    "websocket js",
    "socket io",
    "express routes"
  ],

  "Android Developer": [
    "android",
    "android developer",
    "android dev",
    "apk",
    "kotlin",
    "java android",
    "android studio",
    "jetpack",
    "jetpack compose",
    "xml layout android",
    "activity",
    "fragment",
    "intent",
    "viewmodel",
    "live data",
    "recyclerview",
    "adapter android",
    "android sdk",
    "gradle",
    "material design android",
    "android ui",
    "retrofit",
    "okhttp",
    "room database",
    "sqlite android",
    "mvvm android",
    "android manifest",
    "firebase android",
    "push notification",
    "fcm",
    "android lifecycle",
    "kotlin coroutine",
    "flow kotlin",
    "android navigation",
    "data binding",
    "view binding",
    "apk signing",
    "play store upload",
    "android performance",
    "android permissions",
    "android emulator",
    "android testing",
    "espresso",
    "adb"
  ],

  "iOS Developer": [
    "ios",
    "ios dev",
    "ios developer",
    "swift",
    "swiftui",
    "uikit",
    "xcode",
    "storyboard",
    "cocoapods",
    "swift package manager",
    "spm",
    "plist",
    "viewcontroller",
    "mvvm ios",
    "combine",
    "core data",
    "realm ios",
    "alamo fire",
    "alamofire",
    "api ios",
    "ios layout",
    "auto layout",
    "constraints ios",
    "appstore",
    "testflight",
    "ipa",
    "apple developer",
    "ios certificate",
    "signing ios",
    "provisioning profile",
    "swift concurrency",
    "async await swift",
    "ios lifecycle",
    "ui testing ios",
    "unit testing ios",
    "push notification ios",
    "firebase ios",
    "cloudkit",
    "ios deployment",
    "xcodebuild",
    "swiftui components",
    "ios widgets",
    "scene delegate"
  ],

  "Data Scientist": [
    "data science",
    "data scientist",
    "statistik",
    "statistics",
    "eda",
    "exploratory data analysis",
    "data cleaning",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scikit learn",
    "sklearn",
    "feature engineering",
    "modeling",
    "classification",
    "regression",
    "clustering",
    "kmeans",
    "random forest",
    "xgboost",
    "lightgbm",
    "catboost",
    "data wrangling",
    "sql analytics",
    "big data",
    "spark",
    "pyspark",
    "hadoop",
    "etl",
    "data pipeline",
    "data preprocessing",
    "normalization",
    "standardization",
    "data visualization",
    "hypothesis testing",
    "correlation analysis",
    "anova",
    "time series",
    "arima",
    "forecasting",
    "prediction model",
    "python analytics",
    "jupyter",
    "colab",
    "data storytelling"
  ],

  "DevOps Engineer": [
    "devops",
    "dev ops",
    "ci cd",
    "ci/cd",
    "cicd",
    "docker",
    "dockerfile",
    "containerization",
    "kubernetes",
    "k8s",
    "helm",
    "terraform",
    "ansible",
    "jenkins",
    "gitlab ci",
    "github actions",
    "argo cd",
    "prometheus",
    "grafana",
    "observability",
    "monitoring",
    "alerting",
    "cloud infra",
    "infrastructure as code",
    "iac",
    "sre",
    "site reliability",
    "load balancer",
    "nginx",
    "reverse proxy",
    "ingress",
    "service mesh",
    "istio",
    "open telemetry",
    "linux server",
    "bash scripting",
    "automation engineer",
    "scaling",
    "orchestration",
    "cluster management",
    "devops pipeline",
    "deployment pipeline",
    "blue green deploy",
    "canary deploy",
    "rollout",
    "config management",
    "secrets management",
    "vault"
    ]
}

# contains_word unchanged (kept word-boundary matching)
def contains_word(text: str, word: str):
    return re.search(rf"\b{re.escape(word)}\b", text)

# Revised detect_job_role to disambiguate javascript + backend/front-end
def detect_job_role(user_text: str, profile=None):
    if not user_text:
        user_text = ""
    text = user_text.lower()
    scores = {}

    # 1) count matches per role
    for role, keywords in JOB_ROLE_KEYWORDS.items():
        score = 0
        for kw in keywords:
            if contains_word(text, kw.lower()):
                score += 1
        scores[role] = score

    # 2) special-case disambiguation if text includes 'javascript' or 'node' etc.
    # If user mentioned 'javascript' but also 'backend' / 'node' / 'express' -> boost Back-End JS
    if contains_word(text, "javascript") or contains_word(text, "node") or contains_word(text, "nodejs"):
        if any(contains_word(text, w) for w in ["backend", "server", "express", "api", "rest"]):
            scores["Back-End Developer JavaScript"] += 2
        # If text mentions react/next/vue -> prefer frontend
        if any(contains_word(text, w) for w in ["react", "nextjs", "vue", "svelte"]):
            scores["Front-End Web Developer"] += 2

    # 3) choose highest score
    highest = max(scores.values())
    if highest > 0:
        candidates = [r for r, s in scores.items() if s == highest]
        if len(candidates) == 1:
            return candidates[0]

        # tie-break: if both front and backend tie, favor explicit keywords present
        if "Back-End Developer JavaScript" in candidates and "Front-End Web Developer" in candidates:
            # if explicit backend tokens present -> backend
            if any(contains_word(text, w) for w in ["backend", "node", "express", "server"]):
                return "Back-End Developer JavaScript"
            # if explicit frontend tokens present -> frontend
            if any(contains_word(text, w) for w in ["react", "nextjs", "html", "css", "frontend"]):
                return "Front-End Web Developer"

        # cloud priority as before
        cloud_priority = ["Google Cloud Professional", "DevOps Engineer"]
        for c in cloud_priority:
            if c in candidates:
                return c

        return candidates[0]

    # 4) fallback: check profile.current_focus.course
    if profile:
        cf = profile.get("learning_profile", {}).get("current_focus", {})
        course = (cf.get("course") or "").lower()
        for role, keywords in JOB_ROLE_KEYWORDS.items():
            for kw in keywords:
                if contains_word(course, kw.lower()):
                    return role

    return None
